### ISSUE TITLE
Error on windows when getting object

### ISSUE THREAD

**Issue by lfdversluis** [google/leveldb#325]
I am getting an `IO error: ...\000005.sst: Could not create random access file.` on Windows, but not on any other platform. It seems to be reported [here](https://jira.duraspace.org/browse/FCREPO-1743) as well, but no fix for this to be found. Is there any way to fix this error?

**Comment by cmumford** [comment]
leveldb doesn't directly do any file I/O. It requires that the port implement an leveldb::Env class - so that's up to whoever made this port. leveldb does provide a POSIX Env (src/util/env_posix.cc), but most ports do not use that. leveldb does not provide a Windows Env.

I think to solve this somebody will need to debug the actual Env used in your product. If it's a Windows only bug then look for UNICODE/utf8 path encoding issues, paths which are too long, or permissions issues.
