### ISSUE TITLE
Question: Is there a way to check for the completion of asynchronous operations?

### ISSUE THREAD

**Issue by jplanasc** [google/leveldb#374]
I would be interested in finding a (cost-effective) way to make sure that an asynchronous operation (mainly put operation) is completed. I need to use the asynchronous option, as I would like to do some other work while waiting for operation's completion.

I tried to look for it in the documentation and a bit in the code, but I could not find it.

Thanks in advance.

**Comment by cmumford** [comment]
I'm assuming you're talking about `WriteOptions::sync`. This is only a flag for synchronous file I/O. The put is actually done when `leveldb::DB::Put()` returned, but the data may not be on disk yet, and is instead in a filesystem data buffer.

**Comment by jplanasc** [comment]
Thanks for your answer. I'd like to use asynchronous file I/O (with `WriteOptions::async`) and then, later in the code, check for the completion of this operation. Is there a way to do that with LevelDB? Thanks!

**Comment by cmumford** [comment]
No, if your goal is to know that the transaction is on disk, so that, for example, the power plug could be pulled the instant the transaction is done then you need to do synchronous I/O. But, if you only need to protect against a crash then async I/O is sufficient as the data is now in the filesystem buffers, and will land on disk eventually.

**Comment by jplanasc** [comment]
Ok, I see. I'm more interested in the first use case you mention (knowing when the transaction is on disk). Do you know if there is any future plan to implement this functionality? Thanks for your clarification!
