### ISSUE TITLE
Question: Spread one leveldb over multiple disks ?

### ISSUE THREAD

**Issue by DavidPineauScality** [google/leveldb#480]
Hello,

My company is actively using leveldb as the underlying store for one of our projects.

As we foresee that we'll reach the storage limit of one disk at some point (given our usage of leveldb), we are looking for a solution that would overcome this limitation. Of course, we are thinking about multiple possible solutions, and one of those that seem like the most interesting to us would be to enhance leveldb so that it can write its files (the `.ldb` files) over multiple disks.

Do you know of any similar usage of leveldb and how the problem is addressed ?
Is this something that you would like to see offered as contribution to the project ?
Do you foresee any technical issue to spreading the `.ldb` over multiple disks ?

Cheers,

**Comment by ghemawat** [comment]
On Wed, Jul 5, 2017 at 10:31 AM, David Pineau <notifications@github.com>
wrote:

> Hello,
>
> My company is actively using leveldb as the underlying store for one of
> our projects.
>
> As we foresee that we'll reach the storage limit of one disk at some point
> (given our usage of leveldb), we are looking for a solution that would
> overcome this limitation. Of course, we are thinking about multiple
> possible solutions, and one of those that seem like the most interesting to
> us would be to enhance leveldb so that it can write its files (the .ldb
> files) over multiple disks
>

I think you can achieve this without touching leveldb internals.  Instead,
create a custom implementation of leveldb::Env.  In the custom Env's
NewWritableFile method, pick a disk (or I presume a file-system), create
the file there, and place a symbolic link to that file in the main
directory.  You will also need to change DeleteFile/RenameFile etc. to make
sure they affect both the symbolic link and the real file.

I would much prefer a solution like a custom Env since it keeps
infrequently used functionality out of the core implementation.  Plus it
will give you much more flexibility about your placement decisions.  E.g.,
you could implement arbitrarily complicated rules about which disk to place
some data on.



Do you know of any similar usage of leveldb and how the problem is
> addressed ?
>

 Have you looked into volume managers that can allow a single file-system
to span multiple disks?

Is this something that you would like to see offered as contribution to the
> project ?
>
My guess is that what you end up with will be too specific to be part of
the project.  A separate Env that you maintain is likely the best thing.
If you want to share it with others, you can put it in its own github
repository.

**Comment by DavidPineauScality** [comment]
We had indeed considered using a volume manager underneath a single leveldb; but we were not confident relatively to the performance impact/overhead of the said volume manager, compared to leveldb directly writing to different filesystems. That being said, tests are in order to completely rule out this solution, but we wanted to have this discussion with some leveldb developers (thus yourself) before going further down any of the prospected solutions.

As for the Env definition, we had taken a look at it, but weren't sure if it was the proper way to go, or the proper place to plug ourselves in; and your answer comforts us to go in that direction if this is the retained solution. Your suggestion of symlinks had been a consideration on our side, and I guess that the most important requirement for those is the compatibility with external tools accessing leveldb's data.

**Comment by Liuchang0812** [comment]
You could create a virtual disk via LVM.
