### ISSUE TITLE
A pkg-config file would be useful for linux or macOS

### ISSUE THREAD

**Issue by JaapWijnen** [google/leveldb#658]
As implemented for the old make-based build system in the now closed PR #2. A .pc pkg-config file would be useful for macOS and linux users. I'm trying to write some Swift bindings for example but the pkg-config utility can't find my installed leveldb library.

This was also suggested in #145 but that kind of died with the transition from the make-based build system to cmake.

**Comment by JaapWijnen** [comment]
The only thing we have to add is the following file: leveldb.pc

`prefix=@prefix@
 exec_prefix=${prefix}
 libdir=${exec_prefix}/lib
 includedir=${prefix}/include
 Name: leveldb
 Description: A fast key-value storage
 Version: @version@
 Libs: -L${libdir} -lleveldb
 Cflags: -I${includedir}`

where @version@ should be replaced by the version number of the built version of leveldb. And @prefix@ should be replaced by the folder it is installed in (often /usr/local)
This should be placed somewhere in the leveldb project and then a link to that file should be placed in the pkg-config files location (often /usr/local/lib/pkg-config)

**Comment by cmumford** [comment]
The team considered adding pkg-config support, but decided to stick with the packaging support provided by CMake only for the time being.

**Comment by njwhite** [comment]
Hi @cmumford - can you share the team's reasons? Would you accept a PR for this issue if I submitted one? Thanks -

**Comment by pwnall** [comment]
@njwhite Thank you for volunteering to put together a PR! Unfortunately, we're not currently interested in reviewing pkg-config support.

The main factor here is maintenance cost. We don't use pkg-config, so we wouldn't be testing the support, which means it'd eventually break. We don't want to spend time dealing with this in the future.

A secondary factor is that pkg-config support would open up the flood gates to requests for other useful packaging systems, such as conan, hunter, and vspkg. We want to focus on developing leveldb.

**Comment by SamWilsn** [comment]
I do hate necroposting, but I feel it is justified here.

> The main factor here is maintenance cost. We don't use pkg-config, so we wouldn't be testing the support, which means it'd eventually break. We don't want to spend time dealing with this in the future.

If the pull requester included a test script (perhaps as simple as `gcc $(pkg-config --cflags --libs leveldb) test.c -o test-pc && ./test-pc`), would you change your mind? You'd get an immediate notification of any problems.

> A secondary factor is that pkg-config support would open up the flood gates to requests for other useful packaging systems, such as conan, hunter, and vspkg. We want to focus on developing leveldb.

pkg-config is the [lingua franca](https://en.wikipedia.org/wiki/Lingua_franca) of the "finding a library" world on linux.

For example, [conan supports it](https://docs.conan.io/2/reference/tools/gnu/pkgconfig.html#conan.tools.gnu.PkgConfig), and [cmake supports it](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html) (and by extension, I assume hunter does too.) So does [meson](https://mesonbuild.com/Pkgconfig-module.html), [waf](https://waf.io/apidocs/tools/c_config.html), and [autotools](https://autotools.info/pkgconfig/). I could go on. My point is that you shouldn't need to do any additional work to support more build systems, because pkg-config enables most of them.
