### ISSUE TITLE
Questions about slice in reader

### ISSUE THREAD

**Issue by larrymeng** [google/leveldb#690]
When ReadPhysicalRecord returns a kFullType Record, the record was in the buffer_ not scratch.
Is this a bug? Or special design?
https://github.com/google/leveldb/blob/master/db/log_reader.cc#L104

> scratch->clear();
> *record = fragment;

**Comment by ghemawat** [comment]
This is intentional.  If you look at the specification comment in
log_reader.h, it says:

May use "*scratch" as temporary storage.

Notice the "May".  The implementation can use *scratch, but it does not
have to.


*From: *larrymeng <notifications@github.com>
*Date: *Wed, May 15, 2019 at 8:34 PM
*To: *google/leveldb
*Cc: *Subscribed

When ReadPhysicalRecord returns a kFullType Record, the record was in the

**Comment by cmumford** [comment]
Answered so closing issue. Please reopen for further questions on this topic.
