### ISSUE TITLE
Fail opening database on Windows

### ISSUE THREAD

**Issue by philix** [google/leveldb#743]
On Windows, sometimes, I see a bad `Status` being returned due to failure to remove a `000XXX.dbtmp` file.

I didn't have the chance to copy and paste the message because it was on someone else's computer.

I suspect this is due to some difference in semantics between POSIX and Windows file removal subroutines.

Using the latest `leveldb` version -- 370d532a00581ca79c87af7d7811e56de0ca52a8 (Oct 1 2019).

**Comment by cmumford** [comment]
Possibly, but leveldb does run on other POSIX platforms without error. Other possibilities are anti-virus software, malware, backup software, etc.. If you have a reproducible case where this happens please attach it so that it can be looked into.

**Comment by cmumford** [comment]
Marking question as answered.

**Comment by BengtGustafsson** [comment]
I very often get this error in a test program which repeatedly removes the leveldb directory and then re-creates it in the same directory. The previous leveldb::DB object has been deleted at this point, but I suspect some worker thread has maybe not been properly joined. Here is a typical error message:

"LevelDB error: IO error: testing_database/000002.dbtmp: Unable to remove the file to be replaced."

Sometimes, but rather seldom, I instead get an exception from the std::filesystem::remove_all() call I use to clear the directory which suggests that the issue may be inside Windows: If the previous leveldb instance had some lingering file handes remove_all() should always fail, and it should never succeed whereafter creating a new leveldb instance fails.

**Comment by BengtGustafsson** [comment]
Another possible culprit would be asynchronous file operations that have not completed when the leveldb::DB instance is destroyed. I do all writes via Write of batches, and I don't do any special cleanup activity or waiting between the return of the Write() call on the database and its destruction. I could not find any such functions to call, and I think one should be able to expect the database destructor to ensure that the latest Writes are finished before actually dying.

Deep down this is most likely caused by the difference in how open files are handled in Linux vs Windows, but it is still puzzling that the std::filesystem::remove_all() can clear the directory without error and _then_ leveldb can't create a new database in that directory. The only thing I can think of is a Windows bug that would occur if a process closes a file handle with outstanding asynchronous writes and then immediately deletes the file being written followed by an attempt to create it again (or rename to its name, as it seems to happen here). Obviously Windows should do something better here, but it is conceivable that this type of bug could exist, worst case it could be inside a disk driver maybe. With the Linux model this would not happen as the asynchronous write would happily continue writing to the file that has already been deleted from the directory and creating a new file with the same name does not hinder this.
