### ISSUE TITLE
introducing wyhash hash function

### ISSUE THREAD

**Issue by wangyi-fudan** [google/leveldb#753]
Dear All:
  I would like to introduce wyhash (https://github.com/wangyi-fudan/wyhash)
  It is a 64-bit little endian portable hash function. It is the fastest one that passed all strict hash function tests (https://github.com/rurban/smhasher).  I think leveldb can make use of it to increase performance.

**Comment by pwnall** [comment]
Where are you proposing that LevelDB uses your hash function?

Assuming there is a good answer to the above, I have a technical and a non-technical concern.

1) Technical

You mention that your hash is 64-bit, so I assume it's optimized for 64-bit processors.

We deploy LevelDB on desktop and mobile devices, some of which may run in 32-bit mode. Our deployments use ARM and x86 CPUs. For example, the Chrome browser ships for 32-bit Windows (32-bit x86) and Android (32-bit ARM). LevelDB must perform well on these platforms.

So, before pursuing integrating your hash function into LevelDB, please look into performance on these platforms. If it turns out that your hash function is not a good match for LevelDB, that's perfectly fine -- look for software that only runs on 64-bit machines.

2) Non-technical

Your code's licensing will require extra scrutiny from Google lawyers. Assuming you're asking other folks to adopt your hash function, I suspect you'll run into similar issues.

While I'm not qualified to discuss details, we've published [our guidelines around licensing](https://opensource.google/docs/thirdparty/licenses/). I think that your license falls under [the unencumbered licenses section](https://opensource.google/docs/thirdparty/licenses/#unencumbered).


I hope this helps!

**Comment by wangyi-fudan** [comment]
yes, wyhash can be portable to 32 bit machines ,but the performance will comprimises. Thanks for the discussion, I will develop a 32 bit based hash function.
I choose unlisence because I simply want to make it available for everybody but I don't have any knowledge on lisencing.

**Comment by wangyi-fudan** [comment]
Hi, the new fast quality 64-bit little endian hash function that is efficient on 32 bit machine (wyhash32) is available at https://github.com/wangyi-fudan/wyhash
Just let you know :-)

**Comment by pwnall** [comment]
Assuming we can navigate around the license issue, I still have my main question -- Where are you proposing that LevelDB uses your hash function?

**Comment by wangyi-fudan** [comment]
well, maybe https://github.com/google/leveldb/blob/master/util/hash.cc  could be replaced by wrapping wyhash for better quality (overall speed may not improve significantly) :-)  BTW, it also features the fastest PRNG that pass Bigcrush.

**Comment by ghemawat** [comment]
In addition to the "where in leveldb we might want to use wyhash", it would
be good to know the reasons why it is useful to do so.  So far, I haven't
heard of any existing problems with the current hash function in leveldb
that suggest that it might be useful to switch to a different hash function.

There is always a risk to making changes to widely used libraries like this
one (e.g., perhaps wyhash works poorly for some client's mix of keys, or
since wyhash is new, perhaps there is a class of problems that won't be
discovered until after many people have had a chance to look at it or
analyze it).

Furthermore, note that one of the places Hash() is used is in bloom.cc,
which produces a bloom filter that is stored in persistent storage.  If we
change the hash function, people's stored databases will break since the
bloom filters stored in them will be based on the old hash function.  So at
the very least, the old Hash() implementation will have to be kept.  And I
would be reluctant to add a different hash function to the code base
without:

(1) Some compelling evidence of a problem to be fixed
(2) A proposal for a hash function that lots of people have experience with

**Comment by cmumford** [comment]
Thanks for the idea. Closing issue for now. Reopen if further discussion is necessary.
