### ISSUE TITLE
Release process and the master branch

### ISSUE THREAD

**Issue by elichai** [google/leveldb#776]
Hi,
I'm trying to understand the release process of leveldb.
should the master branch only contain safe to use and vetted code or is it not recommended to use the master branch and only use released versions? 
Is there any vetting/checking/testing that happens on releases that makes it "safer" than master? 

Thanks,
Elichai.

**Comment by cmumford** [comment]
Hi @elichai:

master should be treated as "releasable" for every commit. We run all tests on all platforms for every commit to master before landing a change. Releases get no additional testing - at least not in this project. Other downstream projects, e.g. Chromium, run tests that have the potential of uncovering bugs in leveldb, but it's been a while since that happened.

**Comment by cmumford** [comment]
Closing as answered. Reopen if you have any follow-on questions.
