### ISSUE TITLE
It's not possible to cleanly add an application-specific port.h

### ISSUE THREAD

**Issue by felipecrv** [google/leveldb#824]
I'm rolling my own `leveldb::Env` implementation which I assumed would be completely independent of the leveldb source, but my `Env` will need `snappy` and CRC32 checks and the headers for these two things are defined in `port/port_stdcxx.h` included by `port/port.h` (which is a private header):

```cpp
// Include the appropriate platform specific file below.  If you are
// porting to a new platform, see "port_example.h" for documentation
// of what the new port_<platform>.h file must provide.
#if defined(LEVELDB_PLATFORM_POSIX) || defined(LEVELDB_PLATFORM_WINDOWS)
#include "port/port_stdcxx.h"
#elif defined(LEVELDB_PLATFORM_CHROMIUM)
#include "port/port_chromium.h"
#endif
```

Of course I can ensure I have `snappy` and CRC32 on my side, but ideally both my application and leveldb would use the same entry points for this functionality without me having to ensure leveldb is configured (regarding `snappy` and `crc32c`) exactly the same way my application is.

For Chrome, the problem was "solved" by hardcoding an `ifdef` on `LEVELDB_PLATFORM_CHROMIUM` in `port.h`.

I have two proposed solutions/questions:

 1. Can `snappy` and CRC32 calls become virtual calls on `leveldb::Env`?
 2. Should `port.h` check a build flag (e.g. `LEVELDB_PLATFORM_CUSTOM`) and include a custom application-provided header?

**Comment by philix** [comment]
Interestingly, `port_example.h` contains this comment:

```cpp
// TODO(jorlow): Many of these belong more in the environment class rather than
//               here. We should try moving them and see if it affects perf.
```

**Comment by pwnall** [comment]
1. We have no concrete plans for adding virtual calls to Env for snappy and crc32c. This still seems like the right long-term plan, but we'd need a transition period, which is most likely default implementations that call into the port versions. This is quite a bit of running to stay in the same place. :smile: In other words, this requires quite a bit of work for very little benefit.

2. I'd be more tempted to follow the [googletest approach](https://github.com/google/googletest/tree/master/googletest/include/gtest/internal/custom), which introduces a `custom` directory and asks embedders to manipulate the include path so that #includes resolve to a `custom` directory under their control.

**Comment by pwnall** [comment]
@philix In the short term, you could #define LEVELDB_PLATFORM_CHROMIUM for the LevelDB compilation units, and create a `port/chromium.h` somewhere on your include path.

**Comment by philix** [comment]
@pwnall Thanks for sharing how you see the situation from your side.

I created a `port/port_chromium.h` and it works. It helped that I already had a custom CMakeLists.txt
