### ISSUE TITLE
No space left on device org.iq80.leveldb.DBException: IO error not ceased even after clearing the disk space

### ISSUE THREAD

**Issue by Arshiya95** [google/leveldb#865]
Hi,
We have a java process which uses leveldb for writing the key value pairs to disk and reads those key value pairs on condition basis. We have integrated leveldb with our java application using leveldb-jni-all.jar. Currently we are using leveldb version 1.20 and jni version 1.8.1 in our application .
OS : RHEL 7.4
File System : xfs

When the disk space where the .ldb files are written is completely filled , we see the IO Error:No space on disk . On manually clearing the space also the error has not ceased. 
Please find the error below:    
Error is IO error: /leveldb/db/321532.ldb: No space left on device org.iq80.leveldb.DBException: IO error: /leveldb/db/321532.ldb: No space left on device

Please help us understand the root cause as to why the errors have not ceased even after clearing the file system .

**Comment by pwnall** [comment]
StackOverflow will get you better answers to questions on LevelDB *usage* (as opposed to *development*).

You're using LevelDB through a Java library. This project only handles the C++ implementation, and it's possible that your problem is in the Java wrapper.

A (fairly uneducated) guess is that your database is on a different filesystem than the one you've cleared space for. I think that modern Linux distributions expect your data to live in `/var`. I'm guessing your `/leveldb/db` lives in the `/` filesystem, which can be quite small on some distributions.

Another possibility is that, while you've cleared up some space, it's not enough for the file that LevelDB is trying to write. Note that `.ldb` files grow exponentially in size as a function of their levels. So, you may only see existing `.ldb` files of 1MB and 10MB, and LevelDB might be trying to write its first 100MB file. This applies for any multiple of 10 -- see https://github.com/google/leveldb/blob/master/doc/impl.md#sorted-tables
